### ISSUE TITLE
Custom listView adapter

### ISSUE THREAD

**Issue by aplavin** [yanex/koan#4]
Is it possible (and how) to create a custom adapter for a listview, with a custom layout? ArrayAdapter constructor requires an id of the layout, like here:

            listView {
                adapter = ArrayAdapter(ctx, android.R.layout.simple_list_item_1, listOf("a", "b"))
            }

**Comment by aplavin** [comment]
I also tried to subclass the ArrayAdapter:

            listView {
                adapter = object : ArrayAdapter<String>(ctx, 0, listOf("a", "b")) {
                    override fun getView(position: Int, convertView: View?, parent: ViewGroup): View? {
                        val view = with(parent) {
                            textView {
                                text = "abc"
                            }
                        }
                        return view
                    }
                }
            }

However, this raises an exception: `addView(View) is not supported in AdapterView`. As I understand it's because the DSL calls `addView` on `parent` after creating the view.

**Comment by yanex** [comment]
Koan currently has not special DSL for custom adapters yet.

However, it's quite simple to make your own adapters with Koan. I will modify a [koan-demo-gradle](https://github.com/yanex/koan-demo-gradle) project tomorrow and add some ListView-related code.

**Comment by yanex** [comment]
There was a bug in Koan which made List adapter handling not obvious in the past. With Koan 0.3 there's no problem! Here's the example:

https://github.com/yanex/koan-demo-gradle/blob/master/app/src/main/kotlin/org/example/koandemo/CountriesActivity.kt

**Comment by pasniak** [comment]
the link to Koan does not work
